### ISSUE TITLE
carbon generator wont recreate error GUI when redisconnected

### ISSUE THREAD

**Issue by KRN-8** [Amatsugu/Phos#13]
a connected carbon generator
![obrazek](https://user-images.githubusercontent.com/67783847/86479739-060f0300-bd4d-11ea-89ec-c19f874e2191.png)
destroying all power conduits doesnt disconnect its power
well, it does disconnect it but doesnt remake the error marker

reproduction steps:
1- build Carbon generator
1.5- if it is powered then disconnect it
2- connect it (with power conduit)
3- disconnect it (destroy that power conduit)
4- the error now wont be created (2-3or4 is repeateble loop 1+ times)

**Comment by Amatsugu** [comment]
fixed
