### ISSUE TITLE
wind turbines make variable amounts of power

### ISSUE THREAD

**Issue by KRN-8** [Amatsugu/Phos#14]
the building menu sayes +5/t
is this intended ?

**Comment by Amatsugu** [comment]
that is intended, it changes based on wind speed. The speed of the blades also rotates to show this. Once I get the inspect UI added you will also be able too see info there too

**Comment by KRN-8** [comment]
ye thats what i thought (that it is intended)
but the menu still shows +5/t

**Comment by Amatsugu** [comment]
+5 is the base value. it gets multiplied by the wind power. it can go as low as 0.2x to as high as 2x power. I'll add something to the description to indicate that it is affected by the wind

**Comment by KRN-8** [comment]
then please add precise values (or math formulas) and wind speed indicator (in the top gui?)
