### ISSUE TITLE
build menu nuff(or Not enough) resources indication doesnt update

### ISSUE THREAD

**Issue by KRN-8** [Amatsugu/Phos#16]
the build menu numbers Do NOT Update from Red to white/green indicating i have enough resources once i do
(to build the building)
i have to click in and out of the menu to refresh it

**Comment by Amatsugu** [comment]
can you take a video of when this occurs. I haven't been able to recreate it

**Comment by KRN-8** [comment]
this was yet another copypasta from Discord
i tested it RN and it seems to be fixed (the resource system is still a bit slow and wierd but that belongs to a separate report)

**Comment by Amatsugu** [comment]
Resources are processed every Tick, which I think is currently set to happen every second.
