### ISSUE TITLE
Deleting structures is still broken ;-(

### ISSUE THREAD

**Issue by KRN-8** [Amatsugu/Phos#18]
you can currently delete carbon Thumper Mine
and it will just dealocate the ore tiles and delete upkeep
keeping some of the Models and Resource generation
(soo u can mine infinite amounts of it for free from one ore deposit XD)

**Comment by Amatsugu** [comment]
I haven't been able to reproduce this. Maybe there is more to what is causing it. I'll keep testing but so far nothing.

**Comment by KRN-8** [comment]
ill keep testing too (once im back to testing XD)
im a programmer soo if i dont say Exactly how to reproduce it then i didnt figure it out (and are just informing u that it is a thig)
