### ISSUE TITLE
Conduit spam

### ISSUE THREAD

**Issue by KRN-8** [Amatsugu/Phos#19]
building multiple conduits next to each other will make the last one show GUI Error about not being connected (even thou it IS)
and Deleting them all will make a nice light show XD

![obrazek](https://user-images.githubusercontent.com/67783847/86485812-fa760900-bd59-11ea-9bcb-409398848a00.png)

**Comment by KRN-8** [comment]
it seems to fundamentally break the building system in its vicinity too ;-(

**Comment by KRN-8** [comment]
aaand after building some more in that broken space i cannot build anything anymore ... ;-(

**Comment by KRN-8** [comment]
(the buildings wont place on LMB click anymore)
(before it only happened in the lightshow space, but now everything is broke XD)

**Comment by Amatsugu** [comment]
alright I think I fixed it https://github.com/Amatsugu/Phos/commit/3c6918de126e9fe8971abc916d87de0ebf9c30b5
