### ISSUE TITLE
Losing (or Deleting) HQ doesnt stop resource production

### ISSUE THREAD

**Issue by KRN-8** [Amatsugu/Phos#2]
the HQ resource production isnt tied to the apropriate HQs buildings

**Comment by KRN-8** [comment]
(actually im not sure about this one, it might be ok but better check it out)

**Comment by KRN-8** [comment]
i cannot delete HQ buildings anymore but i bet that if u delete them the production u get from HQ will not stop

**Comment by Amatsugu** [comment]
seems to stop production just fine. But found out the HQ was immortal because it had no collision
