### ISSUE TITLE
SaveLoad after i#19

### ISSUE THREAD

**Issue by KRN-8** [Amatsugu/Phos#23]
ok, loading it was a BAD idea
(i still have the save but dont know how to send it)

![obrazek](https://user-images.githubusercontent.com/67783847/86487145-a3723300-bd5d-11ea-8d6c-ece242544ea0.png)
it disconnected/destroyed all buildings AND created GUI errors for no power above them
and made holes in the map XD

**Comment by KRN-8** [comment]
after game restart and load the holes are gone
but id took another screenshot from more of a angle to show the broken GUI lines
(that might help cause it seems it rotates the GUI Canvas ???)
![obrazek](https://user-images.githubusercontent.com/67783847/86487592-cea95200-bd5e-11ea-9c0b-bb6a0b0ed53b.png)

**Comment by KRN-8** [comment]
this is what shows on first Load
![obrazek](https://user-images.githubusercontent.com/67783847/86487828-7aeb3880-bd5f-11ea-8818-2b2cd56a7374.png)

**Comment by KRN-8** [comment]
and second and every other Load creates the Holes
(maybe somehow split this issue??? dunno probably dont!)

**Comment by Amatsugu** [comment]
fixed, was caused by the same issue as #8
