### ISSUE TITLE
no power error message line points outwards

### ISSUE THREAD

**Issue by KRN-8** [Amatsugu/Phos#24]
![obrazek](https://user-images.githubusercontent.com/67783847/87244411-5832e100-c43d-11ea-96f0-12b3b69ae167.png)
start game
place HQ
name your self
place thumper mine on coal (is what i did)

**Comment by Amatsugu** [comment]
This is so weird. I need to do more testing

**Comment by KRN-8** [comment]
seems to do this always u place a new building outside of power
