### ISSUE TITLE
the Enemy first wolley of shots is shot to the left, as if it didnt aim at all

### ISSUE THREAD

**Issue by KRN-8** [Amatsugu/Phos#3]
currently it shoots to the right and slightly down

**Comment by Amatsugu** [comment]
can you give a video of this. I'm pretty sure I fixed this with this change https://github.com/Amatsugu/Phos/commit/2039cb21e52a5ee112996a39ac3b6df71ab77a87#diff-ed909fe94f785699a2e1daa01c82ef87R124

**Comment by KRN-8** [comment]
ok it seems to only happen with the OLD Saves
now that they should be uncreatable (and therefore hopefully unloadable) it cannot happen anymore

unless someone goes out of his way
make save in the old version that had this bug and load it in the new one
