### ISSUE TITLE
unDeletable Tech buildings

### ISSUE THREAD

**Issue by KRN-8** [Amatsugu/Phos#33]
deleting tech buildings doesnt kill them, keeps tech unlocks and lets u place new ones (placing new ones will fail thou)

**Comment by Amatsugu** [comment]
Fixed 
![4d905f8ec0274b5b84543c60cd6d15c4](https://user-images.githubusercontent.com/3821184/87758774-14dcc780-c7db-11ea-9e28-8192ee1b7e10.png)
