### ISSUE TITLE
units around the beach edges

### ISSUE THREAD

**Issue by KRN-8** [Amatsugu/Phos#4]
![obrazek](https://user-images.githubusercontent.com/67783847/86476096-24253500-bd46-11ea-8777-67356459cc13.png)
if u move a unit to the edge, it will get stuck

**Comment by Amatsugu** [comment]
fixed for now

**Comment by KRN-8** [comment]
wryyy cannot reopen XD

**Comment by Amatsugu** [comment]
fixed
