### ISSUE TITLE
selection rectangle stuck on selecting with selection

### ISSUE THREAD

**Issue by KRN-8** [Amatsugu/Phos#5]
![obrazek](https://user-images.githubusercontent.com/67783847/86476228-6babc100-bd46-11ea-95d6-411600b07f05.png)
if u ~~have a group of units selected and~~ release the LMB above ~~the selection GUI~~ ANY GUI
the selection rectangle will stay until u LMB click outside all GUI (in game world)

**Comment by Amatsugu** [comment]
fixed
