### ISSUE TITLE
gathering amounts per tile are no longer visible

### ISSUE THREAD

**Issue by KRN-8** [Amatsugu/Phos#6]
the latest update removed this information, soo there is no telling **what** or **how well** a thing can mine specific tiles

**Comment by Amatsugu** [comment]
is this happening for everything? I just tested and it seems to work fine. Is there some special case that breaks it?

**Comment by KRN-8** [comment]
before
![obrazek](https://user-images.githubusercontent.com/67783847/86484746-33f94500-bd57-11ea-9797-3dfc856f947f.png)

after
![obrazek](https://user-images.githubusercontent.com/67783847/86484788-483d4200-bd57-11ea-81c0-7978f6835e2e.png)

**Comment by KRN-8** [comment]
yes, it IS "happening for everything"
(there is nothing below it in the pictures btw.)

**Comment by Amatsugu** [comment]
fixed
