### ISSUE TITLE
F6 then F7 (save and loading) will delete HQ connection

### ISSUE THREAD

**Issue by KRN-8** [Amatsugu/Phos#8]
(soo) everything will freak out, and lots of wierdness (bugs) ensues

to reproduce:
place HQ and conect it with a miner using 2(+?) conduits
press F6 and wait for it to finish
press F7 and wait for it to finish
u will get wierdness on the edges (and reconnecting wont work and make even more buggy behavior)

**Comment by Amatsugu** [comment]
fixed
