### ISSUE TITLE
renameable Loaded HQ

### ISSUE THREAD

**Issue by KRN-8** [Amatsugu/Phos#9]
u can load your previous game before u name your new core/HQ (after restarting the game)
soo u can rename the saved HQ XD

**Comment by Amatsugu** [comment]
You're supposed to be able to rename your HQ by clicking the name, seems that's broken. also that shouldn't happen either.

**Comment by Amatsugu** [comment]
fixed

**Comment by Amatsugu** [comment]
also clicking the name on the top bar lets you change the name again

**Comment by KRN-8** [comment]
i didnt know that was a thing, like Ever
